### ISSUE TITLE
Could you please provide ActivityNet feature?

### ISSUE THREAD

**Issue by zikang12138** [zhang-can/CoLA#4]
hello,Could you please provide ActivityNet feature and  corresponding  file  config.py. Thank you.
My e-mail is zikangyuu@gmail.com

**Comment by tangyuelm** [comment]
Thanks for releasing the codes.
I hope to have the ActivityNet features and configuration file as well. Could you also send one to my e-mail which is YUT51@pitt.edu

**Comment by JosephKKim** [comment]
Thanks for the codes, and nice work!
I hope if you can provide ActivityNet features as you did in previous issue. Thanks!\
My email address is 
deepwork@sogang.ac.kr

**Comment by Qinying-Liu** [comment]
Thank you for the codes!
Would you please send me the features of ActivityNet dataset along with the config files? 
My email address is
lydyc@mail.ustc.edu.cn

**Comment by zhang-can** [comment]
Hi @zikang12138 @tangyuelm @JosephKKim @canbaoburen ,

We have released the features and codebase of our CoLA on ActivityNet v1.2 dataset [here](https://github.com/zhang-can/CoLA/tree/anet12).

**Comment by JosephKKim** [comment]
Dear, Can Zhang
Thank you so much for the helping me. (Providing ActivityNet + answering fps related question) I’m also thankful for releasing your amazing work. I think achieving SoTA performance only adding SniCo loss is really amazing!

Beside issues, I want to ask for the advice for this subject, weakly supervised temporal action localization(WSTAL). I know your very busy working but hope you can  give me nice advices or insights.

I was inspired by many works of this subject including your work CoLA. As a 2nd semester master student, I and my team started to work on this subject for a while.. but it was really hard task to get a better performance.

I think it is mainly due to lack of knowledge as I’m a novice in this field, but also think that annotation and dataset has intrinsic problems plus, low resolution of original videos. After visualizing many works it seems that CAS(Class Activation Score) does NOT represent the action it self, but relating other clues (background, object) for the inference.

In addition, the reason that I think that many models are not focusing on the action it self is because it seems like there are so many false positives.. 
Of course, it could be related to common thresholding method which just simply uses a range of thresholds for inference but I still think that many models are not utilizing action itself as a clue.

My questions are…
# 1
Since SoTA models are showing 42-43% of mAP scores and fully supervised models showing around 50% mAP,  I think WSTAL using I3D + THUMOS and ActivityNet as feature extractor and dataset is almost saturated field… I want to know your opinion of this task(WSTAL). 


# 2
I want to know about the process of your work. From the CoLA paper, your idea is to look for the easy snippets and hard snippets. I guess that by looking into data you made a hypothesis that most of actions are discriminative at their start and end points by contrast, background are discriminative at the middle.

If my guess is right "do you usually look in to the dataset first for starting research?


# 3
I am interested in video understanding tasks… Do you have any advice for mater candidate student who just finished first semester? I really hope to write paper to major conference and pursue Ph.D degree and work abroad in the future.



I really hope to get reply from you.
Sincerely, 
Joseph Kim
